name: advent_calendar
description: Advent calendar, how many days till christmas

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.2

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
  assets:
    - assets/images/